# Generated by Django 5.2.3 on 2025-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lntmain_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnt_di_test',
            name='DI_LED1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
