# Generated by Django 5.2.3 on 2025-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lnt_di_test_di_led1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnt_di_test',
            name='DI_LED1',
        ),
        migrations.AddField(
            model_name='ltmaindetails',
            name='tested_by1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
