# Generated by Django 5.1.6 on 2025-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lnt_di_test_r15_lnt_di_test_r16_lnt_di_test_r17_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LnTSscCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('obseredval', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
