# Generated by Django 5.1.6 on 2025-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lntssccard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lntssccard',
            old_name='channel',
            new_name='obseredval1',
        ),
        migrations.RenameField(
            model_name='lntssccard',
            old_name='obseredval',
            new_name='obseredval2',
        ),
        migrations.RenameField(
            model_name='lntssccard',
            old_name='status',
            new_name='obseredval3',
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='obseredval4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='obseredval5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='obseredval6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='obseredval7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='obseredval8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lntssccard',
            name='status8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
